
CREATE SCHEMA [IF NOT EXISTS] Bank;

CREATE TABLE Bank.CUSTOMER (

 USER_ID NUMBER(10) PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
 FIRSTNAME VARCHAR(36) NOT NULL,
 LASTNAME VARCHAR(36) NOT NULL,
 USER_EMAIL VARCHAR(256) UNIQUE NOT NULL,--email 
 LOGIN_ID VARCHAR(256) UNIQUE NOT NULL, 
 LOGIN_PASSWORD VARCHAR(36) NOT NULL 
 AUTHENCATION_TYPE VARCHAR(36) NOT NULL
 ACCOUNT_NUMBER NUMBER(16) --user can be created without account number
 
 
 FOREIGN KEY (ACC_NUMBER) REFERENCES BK_ACCOUNTS(ACC_ID),

);

CREATE TABLE Bank.Account (
 
 ACC_ID NUMBER(16) PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
 ACC_TYPE_ID NUMBER(10) NOT NULL,
 ACC_OWNER NUMBER(10) NOT NULL,
 ACC_BALANCE NUMBER(12) NOT NULL,
 
 FOREIGN KEY (ACC_TYPE_ID) REFERENCES BK_ACCOUNT_TYPES(TYPE_ID),
 FOREIGN KEY (ACC_OWNER) REFERENCES BK_USERS(USER_ID)
 
);
 
CREATE TABLE Bank.ACCOUNT_TYPE (
 
 TYPE_ID NUMBER(10) PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
 ACC_TYPE VARCHAR(24) NOT NULL
 
);-


INSERT INTO BK_ACCOUNT_TYPES (TYPE_ID, ACC_TYPE) VALUES(1, 'CREDIT');
INSERT INTO BK_ACCOUNT_TYPES (TYPE_ID, ACC_TYPE) VALUES(2, 'CHECKING');
INSERT INTO BK_ACCOUNT_TYPES (TYPE_ID, ACC_TYPE) VALUES(3, 'SAVING');

COMMIT;